#!/usr/bin/perl

# readout - Read out text using Speech::Google::TTS
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2013 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use Speech::Google::TTS;
use File::Path qw(make_path);
use Fcntl;
use NDBM_File;

use warnings;
use strict;

my $lang = $ENV{READOUT_LANG};
unless($lang) {
    $lang = $ENV{LANG};
    $lang =~ s/^([^_]+)_.*/$1/;
}
my $cdir = "$ENV{HOME}/.cache/readout";
my $err;

sub mperr($) {
    my $err = shift;
    my @err;

    return unless(@$err);

    for my $diag (@$err) {
	my ($f, $m) = %$diag;
	push(@err, ($f ? "$f: " : '').$m);
    }

    return @err;
}

unless(-d $cdir) {
    make_path($cdir, {error => \$err});
    die "Could not create directory ".join('; ', mperr($err))."\n" if(@$err);
}
my %cache;
tie(%cache, 'NDBM_File', "$cdir/content-$lang", O_RDWR|O_CREAT, 0666);

my $tts = Speech::Google::TTS->new();
$tts->{lang} = $lang;
my $dir = $tts->{tmpdir} = "$cdir/lang-$lang";

foreach my $text (split(/\|/, join(' ', @ARGV))) {

    unless(-d $tts->{tmpdir}) {
	make_path($tts->{tmpdir}, {error => \$err});
	die "Could not create directory ".join('; ', mperr($err))."\n" if(@$err);
    }

    unless($cache{$text}) {
	$tts->say_text($text);
	$cache{$text} = $tts->as_filename();
    }

    print "$cache{$text}\n" if($cache{$text});
}
untie(%cache);

unlink(<$dir/*.mp3>);
